<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Penyakit;
use App\Models\SimulasiBpom;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        // 1. DATA PENYAKIT
        $penyakits = [
            ['kode' => 'P01', 'nama_penyakit' => 'GERD', 'deskripsi' => 'Gastroesophageal Reflux Disease.'],
            ['kode' => 'P02', 'nama_penyakit' => 'Gastritis', 'deskripsi' => 'Peradangan pada dinding lambung.'],
            ['kode' => 'P03', 'nama_penyakit' => 'Tukak Lambung', 'deskripsi' => 'Luka terbuka pada lambung atau duodenum.'],
            ['kode' => 'P04', 'nama_penyakit' => 'Dispepsia', 'deskripsi' => 'Maag Fungsional.'],
            ['kode' => 'P05', 'nama_penyakit' => 'Gastroparesis', 'deskripsi' => 'Gangguan otot lambung lambat kosong.'],
            ['kode' => 'P06', 'nama_penyakit' => 'Hernia Hiatus', 'deskripsi' => 'Kondisi bagian atas lambung mendorong ke atas.'],
            ['kode' => 'P07', 'nama_penyakit' => 'Barrett\'s Esophagus', 'deskripsi' => 'Komplikasi jangka panjang GERD.'],
            ['kode' => 'P08', 'nama_penyakit' => 'Gastroenteritis', 'deskripsi' => 'Infeksi lambung dan usus.']
        ];

        foreach ($penyakits as $p) {
            Penyakit::create($p);
        }

        // Mapping ID Penyakit
        $idGERD = Penyakit::where('kode', 'P01')->first()->id;
        $idGastritis = Penyakit::where('kode', 'P02')->first()->id;
        $idTukak = Penyakit::where('kode', 'P03')->first()->id;
        $idDispepsia = Penyakit::where('kode', 'P04')->first()->id;
        $idGastroparesis = Penyakit::where('kode', 'P05')->first()->id;
        $idHernia = Penyakit::where('kode', 'P06')->first()->id;
        $idBarrett = Penyakit::where('kode', 'P07')->first()->id;
        $idGastroenteritis = Penyakit::where('kode', 'P08')->first()->id;

        // 2. DATA OBAT FULL + LINK PEMBELIAN K24 KLIK
        $obatBpom = [
            // --- GOLONGAN OBAT BEBAS ---
            ['nama_obat' => 'Promag Tablet Kunyah', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idGastritis, 'link_pembelian' => 'https://www.k24klik.com/p/promag-chew-tab-12s-strip-3s-16'],
            ['nama_obat' => 'Promag Suspensi Cair', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idGastritis, 'link_pembelian' => 'https://www.k24klik.com/p/PROMAG-SUSP-60ML-28946'],
            ['nama_obat' => 'Promag Gazero Herbal', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idDispepsia, 'link_pembelian' => 'https://www.k24klik.com/p/promag-herbal-15ml-sach-6s-1754'],
            ['nama_obat' => 'Mylanta Tablet Kunyah', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idGastritis, 'link_pembelian' => 'https://www.k24klik.com/p/MYLANTA-TAB-10S-STRIP-10S-8'],
            ['nama_obat' => 'Mylanta Sirup Suspensi (50ml & 150ml)', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idGERD, 'link_pembelian' => 'https://www.k24klik.com/p/mylanta-susp-150ml-7'],
            ['nama_obat' => 'Mylanta Chew & Melts (Berry/Mint)', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idGastritis, 'link_pembelian' => 'https://www.k24klik.com/p/mylanta-chew&melts-berry-tab-4s-strip-12s-20048'],
            ['nama_obat' => 'Polysilane Tablet Kunyah', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idDispepsia, 'link_pembelian' => 'https://www.k24klik.com/p/POLYSILANE-CHEW-TAB-8S-STRIP-5S-3985'],
            ['nama_obat' => 'Polysilane Suspensi Sirup', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idGastritis, 'link_pembelian' => 'https://www.k24klik.com/p/POLYSILANE-SUSP-100ML-8793'],
            ['nama_obat' => 'Polysilane Junior Kapsul', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idDispepsia, 'link_pembelian' => 'https://www.k24klik.com/p/polysilane-granul-tab-60s-8665'],
            ['nama_obat' => 'Antasida DOEN Erela Tablet Kunyah', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idGastritis, 'link_pembelian' => 'https://www.k24klik.com/p/antasida-doen-erela-chew-tab-100s-2738'],
            ['nama_obat' => 'Antasida DOEN Erela Suspensi 60ml', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idGastritis, 'link_pembelian' => 'https://www.k24klik.com/p/ANTASIDA-DOEN-FM-SUSP-60ML-21788'],
            ['nama_obat' => 'Antasida DOEN Kimia Farma (KF) Tablet', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idDispepsia, 'link_pembelian' => 'https://www.k24klik.com/p/antasida-doen-kf-400mg-tab-1000s-loz-29215'],
            ['nama_obat' => 'Antasida DOEN Kimia Farma (KF) Suspensi', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idGastritis, 'link_pembelian' => 'https://www.k24klik.com/p/antasida-doen-kf-susp-60ml-10197'],
            ['nama_obat' => 'Antasida DOEN Dexa Suspensi 60ml', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idTukak, 'link_pembelian' => 'https://www.k24klik.com/p/antasida-doen-dexa-susp-60ml-24196'],
            ['nama_obat' => 'Antasida DOEN Trifa Tablet', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idDispepsia, 'link_pembelian' => 'https://www.k24klik.com/p/ANTASIDA-DOEN-TRIFA-CHEW-TAB-100S-24973'],
            ['nama_obat' => 'Antasida DOEN Holi Tablet', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idGastritis, 'link_pembelian' => 'https://www.k24klik.com/p/antasida-doen-holi-tab-100s-10193'],
            ['nama_obat' => 'Antasida DOEN Imfarmind Tablet Kunyah', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idTukak, 'link_pembelian' => 'https://www.k24klik.com/p/antasida-doen-imfarmind-chew-tab-100s-24211'],
            ['nama_obat' => 'Antasida DOEN Imfarmind Suspensi 60ml', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idGastritis, 'link_pembelian' => 'https://www.k24klik.com/p/antasida-doen-imfarmind-susp-60ml-29078'],
            ['nama_obat' => 'Antasida DOEN IFI Tablet', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idDispepsia, 'link_pembelian' => 'https://www.halodoc.com/obat-dan-vitamin/antasida-doen-10-tablet'],
            ['nama_obat' => 'Antasida DOEN Mersifarma Tablet Kunyah', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idGastritis, 'link_pembelian' => 'https://www.k24klik.com/p/antasida-doen-mersi-chew-tab-100s-16863'],
            ['nama_obat' => 'Antasida DOEN Mersifarma Suspensi 60ml', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idTukak, 'link_pembelian' => 'https://www.k24klik.com/p/antasida-doen-mersi-susp-60ml-16862'],
            ['nama_obat' => 'Antasida DOEN Lucas Suspensi 60ml', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idGastritis, 'link_pembelian' => 'https://www.k24klik.com/p/antasida-doen-lucas-susp-60ml-24210'],
            ['nama_obat' => 'Antasida DOEN Sanbe Suspensi 60ml', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idTukak, 'link_pembelian' => 'https://www.k24klik.com/p/antasida-doen-sanbe-susp-60ml-10195'],
            ['nama_obat' => 'Antasida DOEN Afi Tablet', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idDispepsia, 'link_pembelian' => 'https://www.k24klik.com/p/antasida-doen-afi-400mg-tab-1000s-loz-24197'],
            ['nama_obat' => 'Sanmag Sirup Suspensi 120ml', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idTukak, 'link_pembelian' => 'https://www.k24klik.com/p/sanmag-susp-120ml-4078'],
            ['nama_obat' => 'Sanmag Forte Suspensi 60ml', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idTukak, 'link_pembelian' => 'https://www.k24klik.com/p/sanmag-f-susp-60ml-16775'],
            ['nama_obat' => 'Bufantacid Forte Sirup 60ml', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idGastritis, 'link_pembelian' => 'https://www.k24klik.com/p/bufantacid-f-susp-60ml-21791'],
            ['nama_obat' => 'Bufantacid Forte Tablet', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idDispepsia, 'link_pembelian' => 'https://www.k24klik.com/p/bufantacid-f-tab-100s-16752'],
            ['nama_obat' => 'Bufantacid Reguler Sirup 100ml', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idTukak, 'link_pembelian' => 'https://www.k24klik.com/p/bufantacid-syr-100ml-16753'],
            ['nama_obat' => 'Bufantacid Reguler Tablet', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idGastritis, 'link_pembelian' => 'https://www.k24klik.com/p/bufantacid-tab-100s-9141'],
            ['nama_obat' => 'Farmacrol Forte Tablet Kunyah', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idHernia, 'link_pembelian' => 'https://www.k24klik.com/p/farmacrol-f-tab-100s-1866'],
            ['nama_obat' => 'Farmacrol Forte Suspensi 100ml & 200ml', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idHernia, 'link_pembelian' => 'https://www.k24klik.com/p/farmacrol-f-susp-200ml-2263'],
            ['nama_obat' => 'Strocain P Tablet', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idTukak, 'link_pembelian' => 'https://www.k24klik.com/p/strocain-p-400mg-tab-10s-strip-10s-8685'],
            ['nama_obat' => 'Xepazym Kaplet Salut Selaput', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idDispepsia, 'link_pembelian' => 'https://www.k24klik.com/p/xepazym-capl-6s-strip-5s-24220'],
            ['nama_obat' => 'Xepazym Tablet', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idDispepsia, 'link_pembelian' => 'https://www.k24klik.com/p/xepazym-tab-50s-15851'],
            ['nama_obat' => 'Polycrol Forte Tablet Kunyah', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idHernia, 'link_pembelian' => 'https://www.k24klik.com/p/polycrol-f-chew-tab-10s-strip-24s-8681'],
            ['nama_obat' => 'Polycrol Forte Sirup Gel 180ml', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idHernia, 'link_pembelian' => 'https://www.k24klik.com/p/polycrol-f-susp-180ml-3052'],
            ['nama_obat' => 'Gastrucid Tablet Kunyah', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idGastritis, 'link_pembelian' => 'https://www.k24klik.com/p/gastrucid-tab-100s-4197'],
            ['nama_obat' => 'Gastrucid Sirup 60ml', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idTukak, 'link_pembelian' => 'https://www.k24klik.com/p/gastrucid-susp-60ml-10143'],
            ['nama_obat' => 'Dexanta Tablet Kunyah', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idGastritis, 'link_pembelian' => 'https://www.k24klik.com/p/dexanta-tab-100s-2806'],
            ['nama_obat' => 'Dexanta Sirup 100ml', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idTukak, 'link_pembelian' => 'https://www.k24klik.com/p/dexanta-susp-100ml-9063'],
            ['nama_obat' => 'Plantacid Forte Tablet', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idDispepsia, 'link_pembelian' => 'https://www.k24klik.com/p/plantacid-f-tab-100s-2041'],
            ['nama_obat' => 'Plantacid Forte Suspensi 100ml', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idTukak, 'link_pembelian' => 'https://www.k24klik.com/p/plantacid-f-susp-100ml-15'],
            ['nama_obat' => 'Plantacid Reguler Tablet Kunyah', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idGastritis, 'link_pembelian' => 'https://www.k24klik.com/p/plantacid-chew-tab-12s-2039'],
            ['nama_obat' => 'Plantacid Reguler Sirup 100ml', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idDispepsia, 'link_pembelian' => 'https://www.k24klik.com/p/PLANTACID-SUSP-100ML-2040'],
            ['nama_obat' => 'Gastrinal HD Tablet', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idHernia, 'link_pembelian' => 'https://www.k24klik.com/p/gastrinal-hd-tab-100s-9874'],
            ['nama_obat' => 'Gastrinal HD Suspensi 120ml', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idGERD, 'link_pembelian' => 'https://www.k24klik.com/p/gastrinal-hd-susp-120ml-16859'],
            ['nama_obat' => 'Stromag Tablet', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idDispepsia, 'link_pembelian' => 'https://www.k24klik.com/p/stromag-tab-100s-16785'],
            ['nama_obat' => 'Lambucid Tablet Kunyah', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idGastritis, 'link_pembelian' => 'https://www.k24klik.com/p/lambucid-chew-tab-10s-strip-20s-10618'],
            ['nama_obat' => 'Lambucid Suspensi 60ml & 100ml', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idTukak, 'link_pembelian' => 'https://www.k24klik.com/p/lambucid-susp-100ml-10616'],
            ['nama_obat' => 'Triocid Sirup 60ml', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idGERD, 'link_pembelian' => 'https://www.k24klik.com/p/triocid-susp-60ml-16798'],
            ['nama_obat' => 'Triocid Tablet Kunyah', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idDispepsia, 'link_pembelian' => 'https://www.k24klik.com/p/triocid-tab-100s-5015'],
            ['nama_obat' => 'Indomag Suspensi 150ml', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idTukak, 'link_pembelian' => 'https://www.k24klik.com/p/indomag-susp-150ml-16861'],
            ['nama_obat' => 'Gestamag Tablet Kunyah', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idTukak, 'link_pembelian' => 'https://www.k24klik.com/p/gestamag-tab-100s-10282'],
            ['nama_obat' => 'Gestamag Suspensi Cair', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idGastritis, 'link_pembelian' => 'https://www.k24klik.com/p/gestamag-susp-170ml-10280'],
            ['nama_obat' => 'Maag Gel Suspensi 60ml', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idGastritis, 'link_pembelian' => 'https://www.k24klik.com/p/maag-gel-susp-60ml-16760'],
            ['nama_obat' => 'Neolanta Serbuk Sachet', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idDispepsia, 'link_pembelian' => 'https://www.k24klik.com/p/neolanta-serbuk-10s-sach-10628'],
            ['nama_obat' => 'Neolanta Tablet Kunyah', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idGastritis, 'link_pembelian' => 'https://www.k24klik.com/p/neolanta-chew-tab-4s-strip-25s-10630'],
            ['nama_obat' => 'Myloxan Suspensi 150ml', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idTukak, 'link_pembelian' => 'https://www.k24klik.com/p/myloxan-susp-150ml-10626'],
            ['nama_obat' => 'Disflatyl Tablet Kunyah', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idDispepsia, 'link_pembelian' => 'https://www.k24klik.com/p/disflatyl-tab-100s-3999'],
            ['nama_obat' => 'Biogastron Tablet', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idDispepsia, 'link_pembelian' => 'https://www.k24klik.com/p/biogastron-tab-100s-14274'],
            ['nama_obat' => 'Anflat Tablet Kunyah', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idGastritis, 'link_pembelian' => 'https://www.k24klik.com/p/anflat-chew-tab-100s-10017'],
            ['nama_obat' => 'Anflat Sirup 100ml', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idTukak, 'link_pembelian' => 'https://www.k24klik.com/p/anflat-susp-100ml-9008'],
            ['nama_obat' => 'Hufamag Plus Tablet Kunyah', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idHernia, 'link_pembelian' => 'https://www.k24klik.com/p/hufamag-plus-tab-100s-10602'],
            ['nama_obat' => 'Hufamag Plus Suspensi Sirup 60ml', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idDispepsia, 'link_pembelian' => 'https://www.k24klik.com/p/hufamag-plus-susp-60ml-10600'],
            ['nama_obat' => 'Gastran Tablet', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idGastritis, 'link_pembelian' => 'https://www.k24klik.com/p/gastran-tab-10s-strip-10s-25509'],
            ['nama_obat' => 'Sismax Sirup Herbal', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idDispepsia, 'link_pembelian' => 'https://www.k24klik.com/p/SISMAX-SYR-120ML-4237'],
            ['nama_obat' => 'Tolak Angin Cair', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idDispepsia, 'link_pembelian' => 'https://www.k24klik.com/p/TOLAK-ANGIN-CAIR-MADU-15ML-SACH-5S-1113'],
            ['nama_obat' => 'Antangin Cair Junior', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idDispepsia, 'link_pembelian' => 'https://www.k24klik.com/p/ANTANGIN-JUNIOR-MADU---MENIRAN-10ML-SACH-5S-2094'],
            ['nama_obat' => 'Redacid Kaplet', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idGastritis, 'link_pembelian' => 'https://www.k24klik.com/p/REDACID-250MG-TAB-30S-2327'],
            ['nama_obat' => 'Waisan Sachet Serbuk', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idDispepsia, 'link_pembelian' => 'https://www.k24klik.com/p/waisan-1g-sach-12s-1524'],
            ['nama_obat' => 'Magalat Tablet Kunyah', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idHernia, 'link_pembelian' => 'https://www.k24klik.com/p/magalat-tab-4s-strip-15s-5801'],
            ['nama_obat' => 'Magalat Sirup 100ml', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idHernia, 'link_pembelian' => 'https://www.k24klik.com/p/magalat-susp-100ml-8895'],
            ['nama_obat' => 'Gestabil Tablet Kunyah', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idTukak, 'link_pembelian' => 'https://www.k24klik.com/p/gestabil-chew-tab-4s-strip-25s-16649'],
            ['nama_obat' => 'Nano Gestabil Pulv Sachet', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idGastritis, 'link_pembelian' => 'https://www.k24klik.com/p/gestabil-nano-pulv-sach-10s-16650'],
            ['nama_obat' => 'Acitral Tablet', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idHernia, 'link_pembelian' => 'https://www.k24klik.com/p/acitral-tab-100s-3451'],
            ['nama_obat' => 'Acitral Suspensi 120ml', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idHernia, 'link_pembelian' => 'https://www.k24klik.com/p/acitral-susp-120ml-3440'],
            ['nama_obat' => 'Lexacrol Chew Tablet', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idGastritis, 'link_pembelian' => 'https://www.k24klik.com/p/lexacrol-chew-tab-150s-1354'],
            ['nama_obat' => 'Lexacrol Forte Sirup 100ml', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idTukak, 'link_pembelian' => 'https://www.k24klik.com/p/lexacrol-f-susp-100ml-10442'],
            ['nama_obat' => 'Magtral Tablet Kunyah', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idDispepsia, 'link_pembelian' => 'https://www.k24klik.com/p/wiacid-150mg-tab-100s-8679'],
            ['nama_obat' => 'Magtral Suspensi 120ml', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idGastritis, 'link_pembelian' => 'https://www.k24klik.com/p/magtral-susp-120ml-9069'],
            ['nama_obat' => 'Magtral Forte Suspensi 120ml', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idTukak, 'link_pembelian' => 'https://www.k24klik.com/p/magtral-f-susp-120ml-9147'],
            ['nama_obat' => 'Magtral Mint Tablet', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idDispepsia, 'link_pembelian' => 'https://www.k24klik.com/p/magtral-mint-tab-100s-24199'],
            ['nama_obat' => 'Magtral Strawberry Tablet', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idDispepsia, 'link_pembelian' => 'https://www.k24klik.com/p/magtral-strawberry-tab-100s-9067'],
            ['nama_obat' => 'Decamag Tablet Kunyah', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idTukak, 'link_pembelian' => 'https://www.k24klik.com/p/decamag-tab-100s-10023'],
            ['nama_obat' => 'Nudramag Tablet', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idGastritis, 'link_pembelian' => 'https://www.k24klik.com/p/nudramag-tab-50s-10648'],
            ['nama_obat' => 'Nudramag Suspensi 60ml', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idTukak, 'link_pembelian' => 'https://www.k24klik.com/p/nudramag-susp-60ml-10646'],
            ['nama_obat' => 'Ultilox Tablet', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idGERD, 'link_pembelian' => 'https://www.k24klik.com/p/ultilox-tab-100s-4391'],
            ['nama_obat' => 'Ultilox Suspensi 150ml', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idDispepsia, 'link_pembelian' => 'https://www.k24klik.com/p/ultilox-susp-150ml-4392'],
            ['nama_obat' => 'Selesmag Tablet Kunyah', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idGastritis, 'link_pembelian' => 'https://www.k24klik.com/p/selesmag-tab-100s-16836'],
            ['nama_obat' => 'Konimag Suspensi Sachet 7ml', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idTukak, 'link_pembelian' => 'https://www.k24klik.com/p/konimag-susp-7ml-sach-30s-9077'],
            ['nama_obat' => 'Trianta Tablet', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idHernia, 'link_pembelian' => 'https://www.k24klik.com/p/trianta-tab-100s-11287'],
            ['nama_obat' => 'Trianta Suspensi 120ml', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idGastritis, 'link_pembelian' => 'https://www.k24klik.com/p/trianta-susp-120ml-16794'],
            ['nama_obat' => 'Berlosid Chew Tablet', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idGastritis, 'link_pembelian' => 'https://www.k24klik.com/p/berlosid-chew-tab-100s-9207'],
            ['nama_obat' => 'Berlosid Suspensi Gel 60ml', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idTukak, 'link_pembelian' => 'https://www.k24klik.com/p/berlosid-susp-60ml-9209'],
            ['nama_obat' => 'Progastric Tablet', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idGastritis, 'link_pembelian' => 'https://www.k24klik.com/p/progastric-tab-200s-10496'],
            ['nama_obat' => 'Ticomag Chew Kaplet', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idTukak, 'link_pembelian' => 'https://www.k24klik.com/p/ticomag-chew-capl-100s-16789'],
            ['nama_obat' => 'Lagesil Tablet', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idDispepsia, 'link_pembelian' => 'https://www.k24klik.com/p/lagesil-tab-100s-2033'],
            ['nama_obat' => 'Lagesil Suspensi 100ml', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idHernia, 'link_pembelian' => 'https://www.k24klik.com/p/lagesil-susp-100ml-24212'],
            ['nama_obat' => 'Lagesil Suspensi 170ml', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idHernia, 'link_pembelian' => 'https://www.k24klik.com/p/lagesil-susp-170ml-4297'],
            ['nama_obat' => 'Novamag Tablet Kunyah', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idGastritis, 'link_pembelian' => 'https://www.k24klik.com/p/novamag-chew-tab-100s-10634'],
            ['nama_obat' => 'Novamag Suspensi 60ml', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idTukak, 'link_pembelian' => 'https://www.k24klik.com/p/novamag-susp-60ml-10636'],
            ['nama_obat' => 'Ranacid Forte Suspensi 100ml', 'golongan' => 'Bebas', 'indikasi_penyakit_id' => $idGastritis, 'link_pembelian' => 'https://www.k24klik.com/p/ranacid-f-susp-100ml-10334'],

            // --- GOLONGAN OBAT BEBAS TERBATAS ---
            ['nama_obat' => 'Promag Double Action Tablet', 'golongan' => 'Bebas Terbatas', 'indikasi_penyakit_id' => $idGERD, 'link_pembelian' => 'https://www.k24klik.com/p/promag-double-action-strip-12s-21792'],
            ['nama_obat' => 'Polysilane Max Peppermint Chew Tab', 'golongan' => 'Bebas Terbatas', 'indikasi_penyakit_id' => $idGERD, 'link_pembelian' => 'https://www.k24klik.com/p/polysilane-max-peppermint-chew-tab-4s-strip-10s-3986'],
            ['nama_obat' => 'Gaviscon Double Action (Liquid/Sachet)', 'golongan' => 'Bebas Terbatas', 'indikasi_penyakit_id' => $idGERD, 'link_pembelian' => 'https://www.doctoroncall.com/id/apotek/obat-bebas-tanpa-resep-otc/gaviscon-peppermint-liquid-200ml'],
            ['nama_obat' => 'Scantoma 375 mg Tablet', 'golongan' => 'Bebas Terbatas', 'indikasi_penyakit_id' => $idGastroenteritis, 'link_pembelian' => 'https://www.k24klik.com/p/scantoma-375mg-tab-100s-16973'],
            ['nama_obat' => 'Neosanmag Fast Tablet Kunyah', 'golongan' => 'Bebas Terbatas', 'indikasi_penyakit_id' => $idGERD, 'link_pembelian' => 'https://www.k24klik.com/p/neosanmag-fast-tab-2s-strip-8s-2037'],
            ['nama_obat' => 'Neosanmag Tablet', 'golongan' => 'Bebas Terbatas', 'indikasi_penyakit_id' => $idGERD, 'link_pembelian' => 'https://www.k24klik.com/p/neosanmag-tab-4s-strip-25s-9073'],

            // --- GOLONGAN OBAT KERAS ---
            ['nama_obat' => 'Omeprazole Novell 20mg Kapsul', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idGERD, 'link_pembelian' => 'https://www.k24klik.com/p/omeprazole-novell-20mg-cap-30s-12'],
            ['nama_obat' => 'Omeprazole Hexpharm 20mg Kapsul', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idGERD, 'link_pembelian' => 'https://www.k24klik.com/p/omeprazole-hexpharm-20mg-cap-30s-8791'],
            ['nama_obat' => 'Omeprazole Sanbe 20mg Kapsul', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idGERD, 'link_pembelian' => 'https://www.k24klik.com/p/omeprazole-sanbe-20mg-cap-30s-10486'],
            ['nama_obat' => 'Omeprazole KF 20mg Kapsul', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idTukak, 'link_pembelian' => 'https://www.k24klik.com/p/omeprazole-kf-20mg-cap-30s-10472'],
            ['nama_obat' => 'Omeprazole Dexa 20mg Kapsul', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idGERD, 'link_pembelian' => 'https://www.k24klik.com/p/OMEPRAZOLE-DEXA-20MG-CAP-100S-24206#'],
            ['nama_obat' => 'Omeprazole Ifars 20mg Kapsul', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idTukak, 'link_pembelian' => 'https://www.k24klik.com/p/OMEPRAZOLE-IFARS-20MG-CAP-30S-28770#'],
            ['nama_obat' => 'Omeprazole Landson 20mg Kapsul', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idGERD, 'link_pembelian' => 'https://www.k24klik.com/p/omeprazole-landson-20mg-cap-30s-10474#'],
            ['nama_obat' => 'Omeprazole IF 20mg Kapsul', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idTukak, 'link_pembelian' => 'https://www.k24klik.com/p/OMEPRAZOLE-IF-20MG-CAP-30S-24203#'],
            ['nama_obat' => 'S-Omevell 20mg Tablet', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idGERD, 'link_pembelian' => 'https://www.k24klik.com/p/S-OMEVELL-20MG-TAB-30S-22616#'],
            ['nama_obat' => 'Lokev 20mg Tablet', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idGERD, 'link_pembelian' => 'https://www.halodoc.com/obat-dan-vitamin/lokev-20-mg-10-kapsul'],
            ['nama_obat' => 'Inhipump 20mg Kapsul', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idTukak, 'link_pembelian' => 'https://www.k24klik.com/p/inhipump-20mg-cap-7s-8787'],
            ['nama_obat' => 'Omed 20mg Kapsul', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idGERD, 'link_pembelian' => 'https://www.halodoc.com/obat-dan-vitamin/omed-20-mg-10-kapsul'],
            ['nama_obat' => 'Omed 40mg Kapsul', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idBarrett, 'link_pembelian' => 'https://www.k24klik.com/p/omed-40mg-cap-20s-16837'],
            ['nama_obat' => 'Ezol 20mg Tablet', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idGERD, 'link_pembelian' => 'https://www.halodoc.com/obat-dan-vitamin/ezol-20-mg-7-tablet'],
            ['nama_obat' => 'Ezol 40mg Tablet', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idBarrett, 'link_pembelian' => 'https://www.k24klik.com/p/ezol-40mg-tab-28s-25508'],
            ['nama_obat' => 'Prohibit 20mg Kapsul', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idTukak, 'link_pembelian' => 'https://www.k24klik.com/p/prohibit-20mg-ecp-cap-14s-10498'],
            ['nama_obat' => 'Lansoprazole Novell 30mg Kapsul', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idGERD, 'link_pembelian' => 'https://www.k24klik.com/p/lansoprazole-novell-30mg-cap-20s-1'],
            ['nama_obat' => 'Lansoprazole Hexpharm 30mg Kapsul', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idTukak, 'link_pembelian' => 'https://www.k24klik.com/p/lansoprazole-hexpharm-30mg-cap-50s-25088'],
            ['nama_obat' => 'Lansoprazole Medikon 30mg Kapsul', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idGERD, 'link_pembelian' => 'https://www.k24klik.com/p/lansoprazole-medikon-30mg-cap-40s-10163'],
            ['nama_obat' => 'Lansoprazole Graha 30mg Kapsul', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idTukak, 'link_pembelian' => 'https://www.k24klik.com/p/lansoprazole-graha-30mg-cap-20s-10161'],
            ['nama_obat' => 'Lansoprazole IF 30mg Kapsul', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idGERD, 'link_pembelian' => 'https://www.k24klik.com/p/lansoprazole-if-30mg-cap-20s-10033'],
            ['nama_obat' => 'Lancid 30mg Kapsul', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idTukak, 'link_pembelian' => 'https://www.halodoc.com/obat-dan-vitamin/lancid-30-mg-10-kapsul'],
            ['nama_obat' => 'Pantoprazole Mahakam 40mg Tablet', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idBarrett, 'link_pembelian' => 'https://www.k24klik.com/p/pantoprazole-mahakam-40mg-tab-10s-9101'],
            ['nama_obat' => 'Prosogan FD 30mg Tablet', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idGERD, 'link_pembelian' => 'https://www.halodoc.com/obat-dan-vitamin/prosogan-fd-30-mg-14-tablet'],
            ['nama_obat' => 'Pantocer 20mg Tablet', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idGERD, 'link_pembelian' => 'https://www.k24klik.com/p/pantocer-20mg-tab-30s-10316'],
            ['nama_obat' => 'Pantocer 40mg Tablet', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idBarrett, 'link_pembelian' => 'https://www.k24klik.com/p/pantocer-40mg-tab-30s-10318'],
            ['nama_obat' => 'Nexium MUPS 20mg Tablet', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idGERD, 'link_pembelian' => 'https://www.k24klik.com/p/nexium-mups-20mg-tab-28s-10'],
            ['nama_obat' => 'Nexium MUPS 40mg Tablet', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idBarrett, 'link_pembelian' => 'https://www.halodoc.com/obat-dan-vitamin/nexium-mups-40-mg-7-tablet'],
            ['nama_obat' => 'Aciblock 150mg Tablet', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idGERD, 'link_pembelian' => 'https://www.halodoc.com/obat-dan-vitamin/aciblock-150-mg-10-tablet'],
            ['nama_obat' => 'Pariet 10mg Tablet', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idTukak, 'link_pembelian' => 'https://www.k24klik.com/p/pariet-10mg-tab-14s-7769'],
            ['nama_obat' => 'Pariet 20mg Tablet', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idGERD, 'link_pembelian' => 'https://www.halodoc.com/obat-dan-vitamin/pariet-20-mg-14-tablet'],
            ['nama_obat' => 'Ranitidine Dexa 150mg Tablet', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idTukak, 'link_pembelian' => 'https://www.k24klik.com/p/ranitidine-dexa-150mg-tab-100s-20'],
            ['nama_obat' => 'Ranitidine Promed 150mg Tablet', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idGastritis, 'link_pembelian' => 'https://www.k24klik.com/p/ranitidine-promed-150mg-tab-100s-22764#'],
            ['nama_obat' => 'Ranitidine Novell 150mg Tablet', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idGERD, 'link_pembelian' => 'https://www.k24klik.com/cari/ranitidine+novell'],
            ['nama_obat' => 'Acran 150mg Tablet', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idGERD, 'link_pembelian' => 'https://www.halodoc.com/obat-dan-vitamin/ranivel-75mg-5-ml-sirup-60-ml'],
            ['nama_obat' => 'Acran 300mg Tablet', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idTukak, 'link_pembelian' => 'https://www.k24klik.com/p/ulsikur-100mg-ml-inj-2ml-ampul-5s-9203#'],
            ['nama_obat' => 'Ranivel 150mg Tablet', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idGastritis, 'link_pembelian' => 'https://www.alodokter.com/aloshop/products/ranivel-150-mg-10-tablet/62a18fbdf15ee840f565f48d'],
            ['nama_obat' => 'Ranivel Sirup', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idGastritis, 'link_pembelian' => 'https://www.alodokter.com/aloshop/products/ranivel-75-mg-sirup-60-ml/61b3806cb5a5e2062d979ce4'],
            ['nama_obat' => 'Zantac 150mg Tablet', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idTukak, 'link_pembelian' => 'https://www.k24klik.com/p/zantac-150mg-tab-30s-4173'],
            ['nama_obat' => 'Tyran 150mg Tablet', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idDispepsia, 'link_pembelian' => 'https://www.k24klik.com/p/tyran-150mg-tab-50s-28852'],
            ['nama_obat' => 'Limaag Tablet 300mg', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idTukak, 'link_pembelian' => 'https://www.k24klik.com/p/limaag-300mg-tab-100s-7833'],
            ['nama_obat' => 'Gastridin Tablet', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idGastritis, 'link_pembelian' => 'https://www.halodoc.com/obat-dan-vitamin/gastridin-150-mg-10-tablet'],
            ['nama_obat' => 'Cimetidine Holi 200mg Tablet', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idTukak, 'link_pembelian' => 'https://www.halodoc.com/obat-dan-vitamin/cimetidine-200-mg-10-tablet'],
            ['nama_obat' => 'Famocid 20mg Tablet', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idGERD, 'link_pembelian' => 'https://www.halodoc.com/obat-dan-vitamin/famocid-20-mg-6-tablet'],
            ['nama_obat' => 'Famocid 40mg Tablet', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idTukak, 'link_pembelian' => 'https://www.halodoc.com/obat-dan-vitamin/famocid-40-mg-6-tablet'],
            ['nama_obat' => 'Sucralfate Dexa 500mg Tablet', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idTukak, 'link_pembelian' => 'https://www.k24klik.com/p/sucralfate-dexa-500mg-tab-100s-24204'],
            ['nama_obat' => 'Sucralfate IF Suspensi 100ml', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idGastritis, 'link_pembelian' => 'https://www.k24klik.com/p/sucralfate-if-500mg-5ml-susp-100ml-29122'],
            ['nama_obat' => 'Sucralfate Mulia Suspensi 100ml', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idTukak, 'link_pembelian' => 'https://www.k24klik.com/p/sucralfate-mulia-500mg-5ml-susp-100ml-29669'],
            ['nama_obat' => 'Sucralfate Tropica Suspensi 100ml', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idGastritis, 'link_pembelian' => 'https://www.k24klik.com/p/sucralfate-tropica-500mg-5ml-susp-100ml-31889'],
            ['nama_obat' => 'Sucralfate Mepro Suspensi 100ml', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idTukak, 'link_pembelian' => 'https://www.k24klik.com/p/sucralfate-mepro-500mg-5ml-susp-100ml-16834'],
            ['nama_obat' => 'Sucralfate Tempo Suspensi 100ml', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idGastritis, 'link_pembelian' => 'https://www.k24klik.com/p/sucralfate-tempo-500mg-5ml-susp-100ml-16832'],
            ['nama_obat' => 'Inpepsa Suspensi 100ml', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idTukak, 'link_pembelian' => 'https://www.halodoc.com/obat-dan-vitamin/inpepsa-suspensi-100-ml'],
            ['nama_obat' => 'Inpepsa Suspensi 200ml', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idGastritis, 'link_pembelian' => 'https://www.k24klik.com/p/inpepsa-500mg-5ml-susp-200ml-36'],
            ['nama_obat' => 'Neciblok Suspensi 100ml', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idTukak, 'link_pembelian' => 'https://www.halodoc.com/obat-dan-vitamin/neciblok-suspensi-100-ml'],
            ['nama_obat' => 'Neciblok Suspensi 200ml', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idGastritis, 'link_pembelian' => 'https://www.halodoc.com/obat-dan-vitamin/neciblok-suspensi-200-ml'],
            ['nama_obat' => 'Nucral Suspensi Sachet', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idGastritis, 'link_pembelian' => 'https://www.halodoc.com/obat-dan-vitamin/nucral-suspensi-sachet-10-ml'],
            ['nama_obat' => 'Episan Suspensi 200ml', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idTukak, 'link_pembelian' => 'https://www.halodoc.com/obat-dan-vitamin/episan-suspensi-200-ml'],
            ['nama_obat' => 'Rebamipide Etercon 100mg Tablet', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idTukak, 'link_pembelian' => 'https://www.k24klik.com/p/rebamipide-etercon-100mg-tab-30s-24201'],
            ['nama_obat' => 'Rebamipide Pratapa Nirmala 100mg Tablet', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idGastritis, 'link_pembelian' => 'https://www.k24klik.com/p/rebamipide-pratapa-nirmala-100mg-tab-30s-16768'],
            ['nama_obat' => 'Mucosta 100mg Tablet', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idTukak, 'link_pembelian' => 'https://www.k24klik.com/p/mucosta-100mg-tab-100s-6'],
            ['nama_obat' => 'Rebamid 100mg Tablet', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idGastritis, 'link_pembelian' => 'https://www.k24klik.com/p/rebamid-100mg-tab-30s-16767'],
            ['nama_obat' => 'Purubex 50mg Kapsul', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idTukak, 'link_pembelian' => 'https://www.k24klik.com/p/purubex-50mg-cap-100s-10510'],
            ['nama_obat' => 'Domperidone Dexa 10mg Tablet', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idGastroparesis, 'link_pembelian' => 'https://www.k24klik.com/p/domperidone-dexa-10mg-tab-100s-24214#'],
            ['nama_obat' => 'Domperidone Hexpharm 10mg Tablet', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idGastroparesis, 'link_pembelian' => 'https://www.k24klik.com/p/domperidone-hexpharm-10mg-tab-100s-21793'],
            ['nama_obat' => 'Domperidone Novell 10mg Tablet', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idDispepsia, 'link_pembelian' => 'https://www.k24klik.com/p/domperidone-novell-10mg-tab-50s-2650'],
            ['nama_obat' => 'Domperidone IF 10mg Tablet', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idGastroparesis, 'link_pembelian' => 'https://www.k24klik.com/p/domperidone-if-10mg-tab-100s-5009'],
            ['nama_obat' => 'Domperidone Erlimpex Sirup 60ml', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idGastroenteritis, 'link_pembelian' => 'https://www.k24klik.com/p/domperidone-erlimpex-5mg-5ml-syr-60ml-24106'],
            ['nama_obat' => 'Vometa 10mg Tablet', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idDispepsia, 'link_pembelian' => 'https://www.halodoc.com/obat-dan-vitamin/vometa-ft-10-mg-10-tablet'],
            ['nama_obat' => 'Vometa Flash 10mg Tablet', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idGastroparesis, 'link_pembelian' => 'https://www.k24klik.com/p/vometa-flash-10mg-tab-50s-31'],
            ['nama_obat' => 'Vometa Drop', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idGastroenteritis, 'link_pembelian' => 'https://www.halodoc.com/obat-dan-vitamin/vometa-drops-10-ml'],
            ['nama_obat' => 'Monell Drop', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idGastroparesis, 'link_pembelian' => 'https://www.halodoc.com/obat-dan-vitamin/monell-drops-10-ml'],
            ['nama_obat' => 'Vomistop Sirup', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idGastroenteritis, 'link_pembelian' => 'https://www.halodoc.com/obat-dan-vitamin/vomistop-sirup-60-ml'],
            ['nama_obat' => 'Galflux 10mg Tablet', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idGastroparesis, 'link_pembelian' => 'https://www.halodoc.com/obat-dan-vitamin/galflux-10-mg-20-tablet'],
            ['nama_obat' => 'Dombaz 10mg Tablet', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idDispepsia, 'link_pembelian' => 'https://www.k24klik.com/p/dombaz-10mg-tab-50s-16364'],
            ['nama_obat' => 'Dome Drop 10ml', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idGastroenteritis, 'link_pembelian' => 'https://www.k24klik.com/p/dome-5mg-5ml-drop-10ml-16375'],
            ['nama_obat' => 'Metoclopramide KF 10mg Tablet', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idGastroparesis, 'link_pembelian' => 'https://www.k24klik.com/p/metoclopramide-kf-10mg-tab-100s-17108'],
            ['nama_obat' => 'Acpulsif 5mg Tablet', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idGastroparesis, 'link_pembelian' => 'https://www.halodoc.com/obat-dan-vitamin/acpulsif-5-mg-10-tablet'],
            ['nama_obat' => 'Buscopan 10mg Tablet', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idGastroenteritis, 'link_pembelian' => 'https://www.k24klik.com/p/buscopan-10mg-tab-100s-407'],
            ['nama_obat' => 'Buscopan Plus Tablet', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idGastroenteritis, 'link_pembelian' => 'https://www.k24klik.com/p/buscopan-plus-tab-100s-408'],
            ['nama_obat' => 'Scopma 10mg Tablet', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idGastroenteritis, 'link_pembelian' => 'https://www.k24klik.com/p/scopma-10mg-tab-100s-15702'],
            ['nama_obat' => 'Scopma Plus Tablet', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idGastroenteritis, 'link_pembelian' => 'https://www.halodoc.com/obat-dan-vitamin/scopma-plus-10-kaplet'],
            ['nama_obat' => 'Hyscopan 10mg Tablet', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idGastroenteritis, 'link_pembelian' => 'https://www.k24klik.com/p/hyscopan-10mg-tab-100s-16924'],
            ['nama_obat' => 'Hyoscine Butylbromide Rama 10mg Tablet', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idGastroenteritis, 'link_pembelian' => 'https://www.k24klik.com/p/hyoscine-butylbromide-rama-10mg-tab-100s-16923'],
            ['nama_obat' => 'Irbosyd 135mg Tablet', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idGastroenteritis, 'link_pembelian' => 'https://www.k24klik.com/p/irbosyd-135mg-tab-30s-3767'],
            ['nama_obat' => 'Braxidin Tablet', 'golongan' => 'Keras', 'indikasi_penyakit_id' => $idTukak, 'link_pembelian' => 'https://www.farmaku.com/product/braxidine'],
        ];

        foreach ($obatBpom as $obat) {
            SimulasiBpom::create($obat);
        }

        // Panggil seeder pakar di akhir
        $this->call(PakarSeeder::class);
    }
}